package com.riseofthebird.data;

/**
 * A playable bird projectile, modelled as a sum type over its concrete kinds.
 *
 * <p>Every bird carries a {@link BirdState} component (its in-flight physics
 * and visual state); kind-specific extras live on the implementing record
 * (e.g. {@link Thord} carries a {@link Lightning} bolt; {@link Bulk} does
 * not). This is the canonical "make illegal states unrepresentable" win:
 * the type system structurally forbids a {@code Bulk} from owning a
 * lightning bolt, so the loop never has to check.
 *
 * <p>Operations on birds are not methods on this interface; they live in
 * {@link com.riseofthebird.logic.Birds} and dispatch via exhaustive
 * {@code switch} expressions over the sealed hierarchy. Adding a new bird
 * kind therefore requires touching every such switch - the compiler will
 * refuse to forget one.
 *
 * <p>Note: this interface intentionally declares no {@code withState}-style
 * contract. Each concrete bird record provides its own
 * {@code withState(BirdState)} (generated by RecordBuilder via the kind's
 * {@code With} marker interface) returning the concrete record type, which
 * is more useful at call sites than a {@code Bird} return would be.
 * The cross-kind state replacement helper lives in
 * {@link com.riseofthebird.logic.Birds#replaceState(Bird, BirdState)} and
 * dispatches over the sealed hierarchy.
 */
public sealed interface Bird permits Thord, Bulk {
    /** Shared physics and visual state every bird carries. */
    BirdState state();
}
